# Generated by Django 3.1.14 on 2023-03-24 16:59

from django.db import migrations, models
import random

def set_ip_address(apps, schema_editor):
    TrafficSignals = apps.get_model('main', 'TrafficSignals')
    for signals in TrafficSignals.objects.all():
        signals.ip_address = '.'.join(str(random.randint(0, 255)) for _ in range(4))
        signals.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230322_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficsignals',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.RunPython(set_ip_address),
    ]
